

-- ####################################################################################################
-- 기존 테이블 수정 SCRIPT
-- ####################################################################################################

ALTER TABLE TBL_SYNONYM ALTER COLUMN WORD nvarchar(200) NOT NULL;
ALTER TABLE TBL_SYNONYM ALTER COLUMN SYNONYM nvarchar(400) NOT NULL;

-- ####################################################################################################
-- DDL
-- ####################################################################################################

-- 유의어
DROP TABLE TBL_WORD_SYNON;
CREATE TABLE TBL_WORD_SYNON (
    WORD_SEQ numeric NOT NULL IDENTITY(10001,1) PRIMARY KEY,
	WORD nvarchar (200) NOT NULL,
	SYNONYM nvarchar (500) NULL
);
CREATE UNIQUE INDEX PK_TBL_WORD_SYNON ON TBL_WORD_SYNON (WORD_SEQ ASC);
--ALTER TABLE TBL_SYNONYM ADD CONSTRAINT TBL_SYNONYM_PK PRIMARY KEY (WORD);


-- 유의어 점수
DROP TABLE TBL_SYNON_SCORE;
DROP TABLE TBL_WORD_SYNON_SCORE;
CREATE TABLE TBL_WORD_SYNON_SCORE (
	WORD_SEQ numeric NOT NULL,
    SYNON_SEQ numeric NOT NULL IDENTITY(10001,1) PRIMARY KEY,
	WORD nvarchar (200) NOT NULL,
	WORD_SYNON nvarchar (200) NOT NULL,
	WORD_SYNON_SCORE numeric NULL default 0,
	SYNONYM nvarchar (400) NULL
);

--CONSTRAINT TBL_SYNON_SCORE_PK PRIMARY KEY (ID,LastName)
--ALTER TABLE TBL_SYNON_SCORE DROP CONSTRAINT PK_TBL_SYNON_SCORE
CREATE UNIQUE INDEX PK_TBL_WORD_SYNON_SCORE ON TBL_WORD_SYNON_SCORE (SYNON_SEQ ASC);
CREATE UNIQUE INDEX PK_TBL_WORD_SYNON_SCORE ON TBL_WORD_SYNON_SCORE (WORD ASC, SYNONYM ASC, SYNON_WORD ASC);
--ALTER TABLE TBL_SYNON_SCORE ADD CONSTRAINT TBL_SYNON_SCORE_PK PRIMARY KEY (WORD, SYNON_WORD);


-- ####################################################################################################
-- DML
-- ####################################################################################################

-- make tbl_word_synon 테이블
INSERT INTO TBL_WORD_SYNON (WORD, SYNONYM) SELECT WORD, SYNONYM FROM TBL_SYNONYM;

-- select multi rows from one column
WITH TMP(WORD_SEQ, WORD, WORD_SYNON, TMP_SYNONYM, SYNONYM) AS (
SELECT WORD_SEQ, WORD,
	CONVERT(NVARCHAR, LEFT(SYNONYM, CHARINDEX(',',SYNONYM+',')-1)),
    STUFF(SYNONYM, 1, CHARINDEX(',',SYNONYM+','), ''),
	SYNONYM
FROM TBL_WORD_SYNON
UNION ALL
SELECT WORD_SEQ, WORD,
	CONVERT(NVARCHAR, LEFT(TMP_SYNONYM, CHARINDEX(',',TMP_SYNONYM+',')-1)),
    STUFF(TMP_SYNONYM, 1, CHARINDEX(',',TMP_SYNONYM+','), ''),
	SYNONYM
FROM TMP
WHERE TMP_SYNONYM > ''
)
INSERT INTO TBL_WORD_SYNON_SCORE (WORD_SEQ, WORD, WORD_SYNON, WORD_SYNON_SCORE, SYNONYM)
SELECT DISTINCT
WORD_SEQ, WORD, WORD_SYNON, 0, SYNONYM
FROM TMP
ORDER BY WORD


-- select multi rows into one column
SELECT 
   SS.WORD,
   STUFF((SELECT ',' + US.WORD_SYNON 
          FROM TBL_WORD_SYNON_SCORE US
          WHERE US.WORD = SS.WORD
          ORDER BY WORD_SYNON_SCORE DESC
          FOR XML PATH('')), 1, 1, '') [SYNON_WORDS]
FROM TBL_WORD_SYNON_SCORE SS
GROUP BY SS.WORD
ORDER BY SS.WORD

-- 동의어 스코어 테이블
UPDATE TBL_WORD_SYNON_SCORE
SET SYNON_WORD_SCORE = (SYNON_WORD_SCORE + 1)
WHERE WORD_SEQ = '' AND SYNON_SEQ = ''

-- TBL_SYNON_SCORE 동의어 스코어 테이블 
SELECT WORD, SYNONYM, SYNON_WORD, CNT FROM (
SELECT WORD, SYNONYM, SYNON_WORD, COUNT(1) CNT FROM TBL_SYNON_SCORE GROUP BY WORD, SYNONYM, SYNON_WORD
) XX WHERE CNT > 1


